apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: igc-health-check
  labels:
    version: 0.0.0
spec:
  inputs:
    resources:
      - name: source
        type: git
      - name: image
        type: image
    params:
      - name: js-image
        type: string
        default: docker.io/node:12-stretch
      - name: tools-image
        type: string
        default: garagecatalyst/ibmcloud-dev:1.0.10
  steps:
    - name: health-check
      image: $(inputs.params.tools-image)
      workingdir: $(inputs.resources.source.path)
      env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      envFrom:
        - configMapRef:
            name: ibmcloud-config
      command: ["/bin/bash"]
      args:
        - -c
        - |
          ENVIRONMENT_NAME="${NAMESPACE}"

          IMAGE_NAME=$(basename -s .git `git config --get remote.origin.url` | tr '[:upper:]' '[:lower:]' | sed 's/_/-/g')

          if [[ "${CLUSTER_TYPE}" == "openshift" ]]; then
              ROUTE_HOST=$(kubectl get route/${IMAGE_NAME} --namespace ${ENVIRONMENT_NAME} --output=jsonpath='{ .spec.host }')
              URL="https://${ROUTE_HOST}"
          else
              INGRESS_HOST=$(kubectl get ingress/${IMAGE_NAME} --namespace ${ENVIRONMENT_NAME} --output=jsonpath='{ .spec.rules[0].host }')
              URL="http://${INGRESS_HOST}"
          fi

          sleep_countdown=5

          # sleep for 10 seconds to allow enough time for the server to start
          sleep 10
          echo "Health check start"
          while [[ $(curl -sL -w "%{http_code}\\n" "${URL}/health" -o /dev/null --connect-timeout 3 --max-time 5 --retry 3 --retry-max-time 30) != "200" ]]; do
              sleep 30
              echo "Health check failure. Remaining retries: $sleep_countdown"
              sleep_countdown=$((sleep_countdown-1))
              if [[ $sleep_countdown -eq 0 ]]; then
                      echo "Could not reach health endpoint: ${URL}/health"
                      exit 1;
              fi
          done

          echo "Successfully reached health endpoint: ${URL}/health"
          echo "====================================================================="
