apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: igc-build-push
spec:
  inputs:
    resources:
      - name: source
        type: git
    params:
      - name: BUILDER_IMAGE
        default: quay.io/buildah/stable:v1.9.0
      - name: DOCKERFILE
        default: ./Dockerfile
      - name: TLSVERIFY
        default: "false"
  outputs:
    resources:
      - name: image
        type: image
  steps:
    - name: build
      image: ${inputs.params.BUILDER_IMAGE}
      workingdir: ${inputs.resources.source.path}
      command: ["buildah"]
      args:
        - "bud"
        - "--tls-verify=${inputs.params.TLSVERIFY}"
        - "--format=docker"
        - "-f"
        - "${inputs.params.DOCKERFILE}"
        - "-t"
        - "${outputs.resources.image.url}"
        - "."
      volumeMounts:
        - mountPath: /var/lib/containers
          name: varlibcontainers
      securityContext:
        privileged: true
    - name: push
      image: appsody/appsody-buildah
      workingdir: ${inputs.resources.source.path}
      command: ["buildah"]
      args:
        - "push"
        - "--tls-verify=${inputs.params.TLSVERIFY}"
        - "${outputs.resources.image.url}"
        - "docker://${outputs.resources.image.url}"
      volumeMounts:
        - mountPath: /var/lib/containers
          name: varlibcontainers
      securityContext:
        privileged: true
  volumes:
    - name: varlibcontainers
      emptyDir: {}
