apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: igc-nodejs-test
spec:
  inputs:
    resources:
      - name: source
        type: git
    params:
      - name: js-image
        type: string
        default: node:12-stretch
  stepTemplate:
    envFrom:
      - configMapRef:
          name: pactbroker-config
  steps:
    - name: build
      image: ${inputs.params.js-image}
      workingdir: ${inputs.resources.source.path}
      command: ["/bin/bash"]
      args:
        - -c
        - |
          set -e
          npm install
          if [ -d client ]; then
            pushd client
            npm install
            popd
          fi
          npm run build
    - name: test
      image: ${inputs.params.js-image}
      workingdir: ${inputs.resources.source.path}
      command: ["/bin/bash"]
      args:
        - -c
        - |
          set -e
          npm test
    - name: publish-pact
      image: ${inputs.params.js-image}
      workingdir: ${inputs.resources.source.path}
      command: ["/bin/bash"]
      args:
        - -c
        - |
          set -e
          if [ -n "${PACTBROKER_URL}" ] && [ -f "test/pact-publish.ts" ]; then
              npm run pact:publish
          else 
              echo "Skipping Pact publish"
          fi
    - name: verify-pact
      image: ${inputs.params.js-image}
      workingdir: ${inputs.resources.source.path}
      command: ["/bin/bash"]
      args:
        - -c
        - |
          set -e
          if [ -n "${PACTBROKER_URL}" ] && [ -f "test/pact-verify.ts" ]; then
              npm run pact:verify
          else 
              echo "Skipping Pact publish"
          fi
    - name: sonar-scan
      image: ${inputs.params.js-image}
      workingdir: ${inputs.resources.source.path}
      envFrom:
        - configMapRef:
            name: sonarqube-config
        - secretRef:
            name: sonarqube-access
      env:
        - name: SONAR_USER_HOME
          value: ${inputs.resources.source.path}
      command: ["/bin/bash"]
      args:
        - -c
        - |
          set -e
          if [ -n "${SONARQUBE_URL}" ] && [ -f "test/sonarqube-scan.ts" ]; then
              npm run sonarqube:scan
          else 
              echo "Skipping Sonar Qube step"
          fi
